### PR TITLE
Php doc

### PR DESCRIPTION
**Pull request by JBlond**

### CODE REVIEW

**Comment by todomagichere** [comment]
This repository is only made for cloning official FPDF releases which are available at: http://www.fpdf.org THERE WILL BE NO DEVELOPMENT IN THIS REPOSITORY!

**Comment by JanSlabon** [comment]
@JBlond, thank you for this commit. As @todomagichere wrote this is only a clone of the original package and there is no development done in this repository. I took you composer.json update and pushed this into the master. The type phpDoc update needs to be contributed to the offical version.

**Comment by JBlond** [comment]
> The type phpDoc update needs to be contributed to the offical version.
@JanSlabon How do I do that?

**Comment by JanSlabon** [comment]
Through the official author: http://fpdf.org/ (Olivier: oliver@fpdf.org)

**Pull request closed without merging**
